### ISSUE TITLE
add latest snippets that are missing

### ISSUE THREAD

**Issue by stjordanis** [fssnippets/fssnip-data#1]
Could you please post a code scraping snippet for downloading the missing fssnip snippets or update the repo? It's stopped at June 2020
@tpetricek  
thank you

**Comment by tpetricek** [comment]
Hi @stjordanis! 

I just updated the data in the https://github.com/fssnippets/fssnip-data repository. Thanks for a useful reminder about this! It's good to have a backup here too.

I did this using a download script added to https://github.com/fssnippets/fssnip-tools, but I'm afraid this requires a connection string that I'm not sharing publicly (but maybe there's a way to create a readonly one...)
